### ISSUE TITLE
Call out need to avoid service network

### ISSUE THREAD

**Issue by jonnywillmac** [ibm-cloud-docs/vpc-on-classic-network#2]
Whilst the docs make it clear RFC1918 address space should be used.  Any range can be.  Can a note be added here to recommend avoiding any service networks used within IBM Cloud?

**Comment by lilorozco** [comment]
Hi! We do warn user to avoid service networks when using a classic access VPC.

https://cloud.ibm.com/docs/vpc-on-classic-network?topic=vpc-on-classic-setting-up-access-to-your-classic-infrastructure-from-vpc

Do you think this needs to be somewhere else?

**Comment by jonnywillmac** [comment]
Hi - yeah, I think it should also be here

https://cloud.ibm.com/docs/vpc-on-classic-network?topic=vpc-on-classic-network-choosing-ip-ranges-for-your-vpc

You may not be planning classic access at that time, or not go as far as the classic access piece and just tick the box.

**Comment by jayhawk87** [comment]
The service networks in question are located outside of the RFC 1918 address space.

What I think we should do is reinforce the net 10 warning from the Classic Access page in the Choosing IP ranges page.

**Comment by lilorozco** [comment]
We've added the following

`When choosing IP ranges for a Classic Access VPC, remember that all subnets will be shared into the Classic Infrastructure VRF, which uses IP addresses in the 10.0.0.0/8 space. To avoid IP address conflicts, do not use IP addresses on the 10.0.0.0/8 space when creating subnets in a Classic Access VPC.`

https://cloud.ibm.com/docs/vpc-on-classic-network?topic=vpc-on-classic-network-choosing-ip-ranges-for-your-vpc
