### ISSUE TITLE
Setting up advanced routing: Clarify picture in first example

### ISSUE THREAD

**Issue by jayhawk87** [ibm-cloud-docs/vpc-on-classic-network#3]
The first picture of https://cloud.ibm.com/docs/vpc-on-classic-network?topic=vpc-on-classic-network-setting-up-advanced-routing-in-vpc includes additional text and a dangling VPC route table. This extra information is confusing users as it implies that the customer is supposed to set up the vpc route themselves, when in fact, it is set up by configuring the VPN connection.

**Comment by lilorozco** [comment]
Good point, going to remove scenario 1 from the custom route topic. Production docs should get updated tomorrow, Sept 6.

**Comment by Louisshin001** [comment]
Customer has the following questions.
1) Can you share a useful example of VPC routes, because all the examples is currently not adequate ?
2) Let me know once the docs is updated.

Do we have any other example doc?

**Comment by Louisshin001** [comment]
Can someone please update me with the above questions?

**Comment by jayhawk87** [comment]
@Louisshin001 the docs have been updated and the remaining use case is valid

That being said, folks are continuing to explore other use cases.
