### ISSUE TITLE
Matching local and peer subnets in output for VPNaaS on VPC doc

### ISSUE THREAD

**Issue by calvinrzachman** [ibm-cloud-docs/vpc-on-classic-network#6]
Hi guys. I noticed a very small typo in the sample output for Step 4. The local and peer CIDRs are exactly the same. I think the local CIDR field should instead read `192.168.0.0/24` so that it mirrors the sample output from Step 3.

```
"local_cidrs": [
        "192.168.0.0/24"
    ],
    "peer_cidrs": [
        "192.168.100.0/24"
    ],
```

Link to doc: https://cloud.ibm.com/docs/vpc-on-classic-network?topic=vpc-on-classic-network---using-vpn-with-your-vpc#step-4-create-a-vpn-connection-from-the-second-vpn-gateway-to-the-first-vpn-gateway

**Comment by johnnyjpixy** [comment]
I have fixed it, New PR is submit. Thanks for your information.

**Comment by austinmama** [comment]
Fixed. Closing.... Thank you!
